from homeassistant.const import Platform

DOMAIN = "intuis_connect"
UPDATE_INTERVAL_SECONDS = 90
PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.SELECT, Platform.CLIMATE]

INTUIS_CLIENT_ID = "59e604948fe283fd4dc7e355"
INTUIS_CLIENT_SECRET = "rAeWu8Y3YqXEPqRJ4BpFzFG98MRXpCcz"
INTUIS_SCOPE = "read_muller write_muller"
INTUIS_USER_PREFIX = "muller"
APP_VERSION = "IntuisConnectHA/1.0"

CLIENT_ID = INTUIS_CLIENT_ID
CLIENT_SECRET = INTUIS_CLIENT_SECRET
AUTH_SCOPE = INTUIS_SCOPE
USER_PREFIX = INTUIS_USER_PREFIX

